### ISSUE TITLE
[Feature Request]: Make the Arrow Pad Draggable 

### ISSUE THREAD

**Issue by BolisettySujith** [immadisairaj/arrow_pad#1]
@immadisairaj this was a really good package, I was using this package in one of my Flutter apps while using it I got to know that I can't drag the joystick in the screen. Currently, we can only place this joy stick controller in only one place, it would be nice if we have a parameter of something like `isDraggable` if it's `true` we can drag this joy stick anywhere on the screen.

 if you like the feature, I would like to contribute to this issue.

**Comment by immadisairaj** [comment]
Thanks for filing an issue @BolisettySujith 

A few things I need to understand here.

> I can't drag the joystick in the screen.

This isn't actually a joystick. Instead a pad. Inspired by old mp3 player buttons.

And, what is the usecase to drag this? I can't think of much as of now. Can you please list out the usecase on why a drag is required on this widget?

(I meant, what usecase are we trying to solve here?)

With that, we can look on how to proceed.

Meanwhile, if it's required that you need a drag, you can try to wrap this widget with [Draggable](https://api.flutter.dev/flutter/widgets/Draggable-class.html). If there is any problems with it, we can discuss here.

**Comment by BolisettySujith** [comment]
<img src="https://github.com/immadisairaj/arrow_pad/assets/73323807/12f4b24e-72a1-4af0-b0e0-2b116aab2db9" width="40%">

I have an app where a location of a user will be plotted on a map and the map is a fixed size, so when the current location is overlapping with the arrow_pad, I need to manually change the location if I want to see what is under the arrow pad.

Preview:

https://github.com/immadisairaj/arrow_pad/assets/73323807/dc157842-b8a7-47ca-874b-7ec0861f9344


Having a draggable pad will be smooth for my use case. So I just thought of having a feature that makes the arrow_pad draggable to other places on the screen...

We can implement it easily without draggable also:

```
class JoyStickController extends StatefulWidget {
  const JoyStickController({super.key});

  @override
  State<JoyStickController> createState() => _JoyStickControllerState();
}

class _JoyStickControllerState extends State<JoyStickController> {

  double _x = 0;
  double _y = 0;

  @override
  Widget build(BuildContext context) {
    return Positioned(
      right: _x,
      bottom: _y,
      child: GestureDetector(
        onPanUpdate: (values) {
          setState(() {
            _x -= values.delta.dx;
            _y -= values.delta.dy;
          });
        },
        child: ArrowPad(
          height: 120,
          width: 120,
          onPressed: (direction) => print(direction),
        ),
      ),
    );
  }
}
```

**Comment by immadisairaj** [comment]
From what I see, you are wrapping another widget over the pad. And also, this will have us using `StatefulWidget` instead of just `StatelessWidget`.

As, this is simply can be used mostly by wrapping a widget. It can be easily used by anyone is what I feel instead of having it for the whole of the pad.

Also, a small limitation I see here is you are using `Positioned` which needs it to be in a `Stack`.

> having a feature that makes the arrow_pad draggable to other places on the screen

I missed you here, can you explain where this "other places" are?

If I understood correctly, you want to use this widget (with draggable) in other screens in your application. If your use-case is that, you can use the widget you created `JoyStickController` (from your example) in different screens by passing suitable parameters (like callbacks).

My main concern here is, I see it as some additional good to have feature which might cause some performance issue for people who is not using it. Also, it isn't much difficult to do so, I think it's fair we can not proceed with this.

Do let me know of your thoughts in this perspective. If there is anything you like to say, feel free.

**Comment by BolisettySujith** [comment]
> I missed you here, can you explain where this "other places" are?

Other places mean, being to able move the arrow pad to different places in the same screen(Which I have shown in the demo video in the previous comment).

I don't have anything much to say except, we can add an additional parameter `isDraggable` to make it not draggable by default and it can be overridden if we want to use the draggable feature. But it's fine if you feel there will be performance issues, others who want the feature can use it by following the code which I have provided above.

Thanks :+1:

**Comment by immadisairaj** [comment]
It's better we don't include it. Thanks for the request anyway.

And, btw, the app you are making looks great and happy that this package is of use.
